# Jekyll configuration — GitHub Pages compatible
# Site settings
title: "Personal Portfolio"
email: "p.vaish@utwente.nl"
description: >-
  PhD researcher working with efficiency in machine learning and computer vision, applied in the medical domain.
baseurl: ""
url: "tenbatsu24.github.io" # Set to "https://yourusername.github.io" when deploying

# Author profile
author:
  name: P. Vaish (Mei)
  email: "p.vaish@utwente.nl"
  image: "assets/images/profile.png"
  github: "tenbatsu24"
  scholar: "aofbvEQAAAAJ"  # comment out to hide
  linkedin: "puru-vaish-5b77931a7/"  # comment out to hide
  orcid: "0000-0002-5180-5293"  # comment out to hide
  website: "https://enigmach.nl"  # comment out to hide

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    style: monokai

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories:
        - post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      featured: false
      categories:
        - project

# Exclude from processing
exclude:
  - README.md
  - assets/images/svgs
